name = "Rocket"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Hugo + Forestry"
homepage = ""
tags = ['landing-page', 'business', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages']
features = ['responsive']
min_version = "0.1"

[author]
  name = "Rocket"
  homepage = "https://rocket.delivery/"
